version: '2'

services:
    mysql:
        image: mysql
        restart: 'no'
        env_file:
           - ./variables.env
        container_name: mysql_phalcon_demo
    nginx:
        depends_on:
            - phpfpm
        image: nginx
        ports:
            - "80:80"
        restart: 'no'
        working_dir: /var/www
        volumes:
            - ../:/var/www/
            - ./conf/nginx/phalcon.conf:/etc/nginx/conf.d/default.conf
        links:
            - phpfpm

    phpfpm:
        image: phalconphp/php-apache:ubuntu-16.04
        restart: 'no'
        working_dir: /var/www
        ports:
            - "8080:80"
            - "9002:9000"
        volumes:
            - ../:/var/www
            - ./conf/php/php.ini:/opt/docker/etc/php/php.ini
        depends_on:
            - mysql
    phpmyadmin:
        restart: 'no'
        image: phpmyadmin/phpmyadmin:4.6
        depends_on:
          - mysql
        ports:
          - "9090:80"
        env_file:
            - ./variables.env

    # composer:
    #     restart: 'no'
    #     image: phalconphp/composer
    #     command: install --no-dev
    #     working_dir: /var/www
    #     volumes:
    #         - ./phalcon:/var/www

